repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
    -   id: detect-private-key
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: "v0.960"
#     hooks:
#     -   id: mypy
#         name: mypy_petfinder_sync
#         files: ^petfinder_sync/
#         entry: mypy petfinder_sync/
#         pass_filenames: false
#         args: [
#             "--strict",
#             "--ignore-missing-imports",
#             "--exclude=petfinder_sync/build",
#             "--exclude=petfinder_sync/infrastructure",
#             "--exclude=petfinder_sync/run*",
#             "--exclude=petfinder_sync/petfinder_sync/tests"
#         ]
#     -   id: mypy
#         name: mypy_sync_to_rescue_groups
#         files: ^sync_to_rescue_groups/
#         entry: mypy sync_to_rescue_groups/
#         pass_filenames: false
#         args: [
#             "--strict",
#             "--ignore-missing-imports",
#             "--exclude=sync_to_rescue_groups/build",
#             "--exclude=sync_to_rescue_groups/infrastructure",
#             "--exclude=sync_to_rescue_groups/sync_to_rescue_groups/tests",
#         ]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
    -   id: ruff
    -   id: ruff-format
