repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: ["--max-line-length=120"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"
    hooks:
    -   id: mypy
        name: mypy_petfinder_sync
        files: ^petfinder_sync/
        entry: mypy petfinder_sync/
        pass_filenames: false
        args: [
            "--strict",
            "--ignore-missing-imports",
            "--exclude=petfinder_sync/build",
            "--exclude=petfinder_sync/infrastructure",
            "--exclude=petfinder_sync/run*",
            "--exclude=petfinder_sync/petfinder_sync/tests"
        ]
        additional_dependencies: [types-requests>=2.27.29]
    -   id: mypy
        name: mypy_new_digs_to_rescue_groups
        files: ^new_digs_to_rescue_groups/
        entry: mypy new_digs_to_rescue_groups/
        pass_filenames: false
        args: [
            "--strict",
            "--ignore-missing-imports",
            "--exclude=new_digs_to_rescue_groups/build",
            "--exclude=new_digs_to_rescue_groups/infrastructure",
            "--exclude=new_digs_to_rescue_groups/new_digs_to_rescue_groups/tests",
        ]
        additional_dependencies: [types-requests>=2.27.29]
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
